# Generated by Django 4.2.16 on 2024-11-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_fecha_alter_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total_con_servicio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
    ]
