# Generated by Django 4.2.16 on 2024-11-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad', models.CharField(choices=[('kg', 'kilogramos'), ('L', 'litros'), ('oz', 'Onzas'), ('U', 'unidad')], max_length=10)),
            ],
        ),
    ]
