# Generated by Django 4.2.16 on 2024-11-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_ingredienteproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
